#ifndef INJCALCULATOR_HXX
#define INJCALCULATOR_HXX

#include <QMainWindow>
#include "CalcusEnj.hxx"
#define T_DEFINE_SIGNATURE_BUTTON_CLICKED( N ) \
    void on_button##N##_clicked();

namespace Ui
{
    class InjCalculator;
}

class InjCalculator : public QMainWindow
{
    Q_OBJECT

  public:
    explicit InjCalculator( QWidget *parent = nullptr );
    ~InjCalculator();

  private slots:
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( 0 )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( 1 )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( 2 )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( 3 )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( 4 )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( 5 )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( 6 )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( 7 )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( 8 )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( 9 )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( C )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Plus )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Min )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Mult )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Div )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Equal )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Sqrt )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Pow )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Tg )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Cos )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Sin )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Pers )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Dot )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( E )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Pi )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Bs )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Ang )
    T_DEFINE_SIGNATURE_BUTTON_CLICKED( Inj )

  private:
    Calcus cEnj;
    Ui::InjCalculator *ui;
    bool afterOp { 0 };
};

#endif // INJCALCULATOR_HXX
